name: Upload release artifacts

on:
  release:
    types: [published]

env:
  VERSION: ${{ github.event.release.name }}
  REPO_NAME: ${{ github.event.repository.name }}
  OUT_FOLDER: ${{ github.event.repository.name }}
  NODE_VERSION: '22.x'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Sanity check
      run: |
        echo "Version: ${{ env.VERSION }}"
        echo "Repository name: ${{ env.REPO_NAME }}"
        echo "Out folder: ${{ env.OUT_FOLDER }}"
        echo "Node version: ${{ env.NODE_VERSION }}"
      shell: bash

    - name: Build plugin
      run: |
       npm install
       npm run build

    - name: Replace version in manifest
      run: |
        sed -i 's/"version": "1.0.0"/"version": "${{ env.VERSION }}"/g' manifest.json

    - name: Create archive
      run: |
        mkdir ${{ env.OUT_FOLDER}}
        mv -t ${{ env.OUT_FOLDER}} main.js manifest.json
        zip -r ${{ env.OUT_FOLDER}}.zip ${{ env.OUT_FOLDER}}
      shell: bash

    - name: Upload artifact
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ env.OUT_FOLDER }}.zip
        asset_name: "${{ env.REPO_NAME }}-${{ env.VERSION }}.zip"
        tag: ${{ github.ref }}
